const COUNTRY_HERO_STYLE = {
  mainBoxStyle: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    px: 2,
    py: { xs: 6, md: 13, lg: 19 },
    maxHeight: '700px',
    borderRadius: '0px 0px 54px 54px',
    borderBottom: '2px solid rgba(0, 0, 0, 0.04)',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    gap: 2,
    textAlign: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  overlayImageStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    opacity: 0.6,
    zIndex: 0,
  },
  titleStyle: {
    mx: 'auto',
    fontSize: 'clamp(20px, 5vw, 71px)',
    width: '95%',
    maxWidth: '1480px',
    fontWeight: 600,
    lineHeight: { xs: 'auto', sm: 1.4 },
    color: '#0B395A',
    mb: 3,
  },
  textStyle: {
    mx: 'auto',
    width: { xs: '90%' },
    fontSize: { xs: '14px', sm: '16px', md: 'clamp(12px, 5vw, 22px)' },
    maxWidth: '1270px',
    color: '#26292B',
    mb: 2,
  },
  buttonStyle: {
    mt: 2,
    width: '65%',
    maxWidth: '213px',
    height: { xs: '38px', md: '44px' },
    color: '#FFFFFF',
    background: 'rgba(2, 152, 148, 1)',
    border: '2px solid rgba(27, 202, 198, 0.47)',
    borderRadius: '10px',
    fontSize: { xs: '14px', md: '18px', lg: '21px' },
    px: 4,
    py: 1.5,
    textTransform: 'none',
    textWrap: 'nowrap',
  },
};

const LETS_WORK_TOGETHER_STYLE = {
  mainBoxStyle: { width: '100%' },
  contentBoxStyle: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3.5,
  },
  titleStyle: {
    mx: 'auto',
    width: { xs: '89%', sm: '80%' },
    fontSize: { xs: 'clamp(18px, 5vw, 66px)' },
    maxWidth: '1000px',
    fontWeight: 600,
    lineHeight: { xs: 'auto', sm: 1.4 },
    color: '#0B395A',
    textAlign: 'center',
  },
  textStyle: {
    mx: 'auto',
    width: { xs: '90%', sm: '100%' },
    maxWidth: { xs: '100%', sm: '80%', md: '740px', lg: '1350px' },
    fontSize: { xs: '14px', sm: '16px', md: '20px', lg: '29px' },
    color: '#29292A',
    textAlign: 'center',
    fontWeight: 400,
  },
  relativeBoxStyle: { position: 'relative', zIndex: 1 },
  hrStyle: {
    display: 'none',
    height: '8px',
    width: '100%',
    backgroundColor: 'rgba(183, 175, 175, 0.15)',
    border: 'none',
    position: 'absolute',
    top: '51.5%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 0,
    '@media(min-width: 1024px)': {
      display: 'flex',
    },
  },
  itemsMainBoxStyle: {
    pt: 3.5,
    mx: 'auto',
    px: { md: 2, lg: 1 },
    width: { xs: '100%' },
    maxWidth: '1500px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    zIndex: 1,
  },
  leftDesignImageStyle: {
    width: { md: '110px', lg: '120px' },
    height: { md: '268px', lg: '288px' },
    '@media(max-width: 1023px)': {
      display: 'none',
    },
  },
  itemBoxStyle: {
    py: 4,
    flexGrow: 1,
    display: 'flex',
    justifyContent: 'center',
    borderTop: '5px solid rgba(183, 175, 175, 0.15)',
    borderBottom: '5px solid rgba(183, 175, 175, 0.15)',
    borderLeft: 0,
    borderRight: 0,
    width: '100%',
    maxWidth: '1400px',
    mx: 'auto',
    '@media(min-width: 1024px)': {
      borderTop: '8px solid rgba(183, 175, 175, 0.15)',
      borderBottom: '8px solid rgba(183, 175, 175, 0.15)',
    },
  },
  gridContainerStyle: {
    width: '100%',
    gap: { xs: 3, md: 4, lg: 5 },
    backgroundColor: 'rgba(247, 247, 249, 1)',
  },
  cardStyle: {
    width: '100%',
    minHeight: { xs: '72px', md: '78px', lg: '84px' },
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '23px',
    boxShadow: '-13px 4px 16.1px rgba(24, 84, 153, 0.21)',
    backgroundColor: '#EFEFEF',
    position: 'relative',
    zIndex: 1,
    //   p: 1,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      borderRadius: '23px',
      boxShadow: 'inset 0px -3px 1.7px rgba(0, 0, 0, 0.05)',
      pointerEvents: 'none',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      borderRadius: '23px',
      boxShadow: 'inset 0px 3px 4px rgba(255, 255, 255, 1)',
      pointerEvents: 'none',
    },
  },
  innerCardStyle: {
    width: '99%',
    display: 'flex',
    justifyContent: {
      xs: 'space-evenly',
      md: 'space-between',
    },
    alignItems: 'center',
  },
  ellipseStyle: {
    width: { md: '28px', lg: '31px' },
    display: { xs: 'flex', md: 'flex' },
  },
  cardTextStyle: {
    width: {
      xs: 'calc(80% - 28px)',
      lg: 'calc(100% - 64px)',
    },
    fontWeight: 500,
    color: '#111845',
    textAlign: 'center',
    fontSize: { xs: '12px', md: 'clamp(12px, 1.3vw, 20px)' },
    '@media(max-width:1023px)': {
      width: 'calc(90% - 28px)',
    },
  },
  rightDesignImageStyle: {
    width: { md: '110px', lg: '120px' },
    height: { md: '268px', lg: '288px' },
    '@media(max-width: 1023px)': {
      display: 'none',
    },
  },
};

const COMPARISON_TABLE_STYLE = {
  mainBoxStyle: {
    pt: { xs: 4, md: 5 },
    pb: 3,
    px: { xs: 4, md: 7 },
    borderRadius: '43px',
    color: '#fff',
    width: '92%',
    maxWidth: '1400px',
    mx: 'auto',
    background:
      'linear-gradient(170deg, rgba(0, 28, 99, 1) 25%, rgba(4, 16, 44, 1) 100%)',
  },
  titleStyle: {
    fontSize: { xs: '18px', sm: '23px', md: 'clamp(25px, 1.8vw, 40px)' },
    fontWeight: 600,
    '@media(min-width: 1921px)': {
      fontSize: '35px',
    },
  },
  textStyle: {
    fontSize: { xs: '15.5px', sm: 'clamp(18px, 1.75vw, 31px)' },
    fontWeight: 400,
    color: '#d0d6f9',
    mb: 3.5,
  },
  tableContainerStyle: {
    mx: 'auto',
    width: '95%',
    background: 'transparent',
    boxShadow: 'none',
  },
  tableCellStyle: (index) => ({
    color: '#fff',
    pb: 'auto',
    borderBottom: index === 3 ? 0 : '1px solid rgba(255,255,255,0.3)',
  }),
  columnStyle: {
    fontSize: {
      xs: 'clamp(15px, 1.3vw, 33px)',
    },
  },
  rowStyle: {
    fontSize: {
      xs: 'clamp(15px, 1.3vw, 33px)',
    },
  },
};

const SALARY_DATA_TABLE_STYLE = {
  componentBoxStyle: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#EDF3FF',
    py: 6,
  },
  mainBoxStyle: {
    width: '92%',
    maxWidth: '1400px',
    display: 'flex',
    alignItems: 'center',
  },
  titleAndDescriptionBoxStyle: { px: 6, pb: 4 },
  titleStyle: {
    color: '#0B395A',
    fontSize: { xs: '18px', sm: '23px', md: 'clamp(25px, 1.8vw, 40px)' },
    fontWeight: 600,
    '@media(min-width: 1921px)': {
      fontSize: '40px',
    },
  },
  textStyle: {
    fontSize: { xs: '15.5px', sm: 'clamp(18px, 1.75vw, 31px)' },
    fontWeight: 300,
    color: '#0B395A',
  },
  tebleBoxStyle: {
    width: '100%',
    backgroundColor: '#fff',
    boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.25)',
    borderRadius: '43px',
    p: { xs: 2, lg: 4 },
  },
  tableContainerStyle: {
    mx: 'auto',
    width: '95%',
    color: '#0B395A',
    backgroundColor: 'transparent',
    boxShadow: 'none',
  },
  tableCellStyle: (rowIndex, colIndex) => ({
    color: '#0B395A',
    pt: { xs: rowIndex === 1 ? 2 : 1, lg: rowIndex === 1 ? 3 : 1.5 },
    pb: { xs: 1, lg: 1.5 },
    textAlign: colIndex === 0 ? 'left' : 'center',
    borderBottom: rowIndex === 0 ? '2px solid rgba(179, 170, 170, 0.5)' : 0,
  }),
  columnStyle: {
    fontSize: {
      fontWeight: 500,
      xs: 'clamp(15px, 1.3vw, 33px)',
    },
  },
  rowStyle: {
    fontSize: {
      xs: 'clamp(15px, 1.3vw, 33px)',
    },
  },
};

const RIGHT_CHOICE_FOR_EMPLOYERS_STYLE = {
  mainBoxStyle: {
    mx: 'auto',
    width: '100%',
    maxWidth: '1500px',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 5,
  },
  titleStyle: {
    fontWeight: 600,
    color: '#0B395A',
    fontSize: 'clamp(18px, 5vw, 36px)',
    textAlign: 'center',
    width: { xs: '85%', sm: '80%', lg: '100%' },
  },
  gridStyle: { xs: '90%', md: '98%' },
  cardStyle: {
    width: '100%',
    maxWidth: { xs: '90%', sm: '85%', md: '354px' },
    minHeight: { xs: '70px', md: '80px', lg: '100px' },
    borderRadius: '6.9px',
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'rgba(232, 244, 253, 1)',
    boxShadow: '0px 3.4px 6.45px rgba(135, 128, 128, 0.29)',
    border: '1px solid rgba(17, 24, 69, 0.10)',
    gap: 1,
    py: 0.8,
    px: 1.5,
    mb: 0.8,
  },
  imageStyle: { width: { xs: '45px', md: '58px' }, height: 'auto' },
  cardTitleStyle: {
    fontSize: { xs: 'clamp(15px, 1.4vw, 18px)' },
    fontWeight: 500,
    color: 'rgba(11, 57, 90, 1)',
  },
};

const OUT_SOURCING_SERVICES_STYLE = {
  mainBoxStyle: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
  },
  titleStyle: {
    mx: 'auto',
    width: '92%',
    fontSize: { xs: '18px', sm: 'clamp(23px, 5vw, 52px)' },
    maxWidth: '1250px',
    textAlign: 'center',
    color: '#0B395A',
    fontWeight: 600,
  },
  cardStyle: {
    mx: 'auto',
    width: { xs: '90%', md: '100%' },
    display: 'flex',
    flexDirection: 'column',
    justifyContent: { xs: 'start', md: 'space-between', lg: 'space-between' },
    minHeight: { xs: '340px', md: '475px', lg: '570px' },
    background:
      'linear-gradient(170deg, rgba(0, 28, 99, 1) 25%, rgba(4, 16, 44, 1) 100%)',
    borderRadius: { xs: '40px', lg: '50px' },
    gap: 3,
    pb: { xs: 0, md: 0, lg: 0 },
    '@media(min-width: 1024px) and (max-width:1439px)': {
      minHeight: '570px',
    },
  },
  cardContentBoxStyle: {
    p: { xs: 4, md: 5, lg: 4.5 },
  },
  cardTitleStyle: {
    fontSize: { xs: '17px', sm: 'clamp(20px, 2.3vw, 32px)' },
    minHeight: 'clamp(78px, 6vw, 105px)',
    fontWeight: 600,
    color: '#fff',
    mb: 0.5,
  },
  descriptionStyle: {
    fontSize: 'clamp(14px, 1.8vw, 20px)',
    fontWeight: 400,
    color: '#fff',
  },
  cardImageBoxStyle: {
    mx: 'auto',
    width: '100%',
    display: 'flex',
    alignItems: 'flex-end',
    overflow: 'hidden',
    px: 4,
  },
  cardImageStyle: (maxWidth, origin = 'top left', scale = '1.56') => ({
    mx: 'auto',
    width: { xs: '90%', md: '100%' },
    maxWidth: maxWidth,
    overflow: 'hidden',
    transition: 'transform 0.5s ease-in-out',
    transformOrigin: origin,
    height: '100%',
    objectFit: 'cover',
    position: 'relative',
    '&:hover': {
      transform: `scale(${scale})`,
    },
  }),
};

const COMPANIES_TRUST_STYLE = {
  mainBoxStyle: {
    width: '90%',
    mx: 'auto',
    maxWidth: '1400px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: { xs: 0, md: 4 },
  },
  contentBoxStyle: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    textAlign: 'center',
  },
  titleStyle: {
    mx: 'auto',
    width: '95%',
    fontSize: { xs: '18px', sm: 'clamp(23px, 5vw, 52px)' },
    maxWidth: '1000px',
    fontWeight: 600,
    color: '#0B395A',
  },
  descriptionStyle: {
    fontSize: { xs: '14px', sm: '16px', md: '18px', lg: '20px' },
    fontWeight: 400,
    width: { xs: '80%', md: 'auto' },
    mx: 'auto',
    color: '#111845',
    '@media(min-width: 769px) and (max-width: 1426px)': {
      width: '85%',
    },
  },
  slideStyle: {
    width: '90%',
    maxWidth: '350px',
    paddingBottom: '20px',
  },
  cardStyle: {
    display: { xs: 'none', md: 'flex' },
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: { xs: 'center', md: 'center' },
    width: '100%',
    maxWidth: { md: '320px', lg: '408px' },
    minHeight: { xs: '235px', md: '250px', lg: '303px' },
    backgroundColor: '#FFFFFF',
    border: '1px solid #D6D6D7',
    boxShadow: '-5px 4px 59.8px rgba(24, 84, 153, 0.2)',
    borderRadius: '20px',
    textAlign: 'center',
    py: 1.5,
    px: 2,
    '@media(min-width: 400px) and (max-width: 481px)': {
      minHeight: '215px',
    },
  },
  titleAndDescripitonBoxStyle: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0.8,
    mt: 0.8,
  },
  imageStyle: { width: { xs: '55px', lg: 'auto' }, height: 'auto' },
  cardTitleStyle: {
    fontSize: { xs: '16px', sm: '18px', lg: '23px' },
    fontWeight: 500,
    color: '#111845',
    minHeight: '25px',
    '@media(min-width: 0px) and (max-width: 383px)': {
      minHeight: '50px',
    },
  },
  cardDescriptionStyle: {
    fontSize: { xs: '11px', sm: '13px', lg: '17px' },
    fontWeight: 400,
    color: '#57585C',
    minHeight: '85px',
  },
};

const DASHBOARD_HERO_STYLE = {
  mainBoxStyle: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: 4,
    px: 3,
  },
  titleStyle: {
    mx: 'auto',
    width: '95%',
    fontSize: { xs: '18px', sm: 'clamp(23px, 5vw, 52px)' },
    maxWidth: '1000px',
    fontWeight: 600,
    color: '#0B395A',
  },
  imageBoxStyle: {
    mx: 'auto',
    width: 'auto',
    backgroundColor: 'rgba(130, 141, 215, 0.44)',
    display: 'flex',
    justifyContent: 'center',
    borderRadius: { xs: '15px 15px 0px 0px', sm: '26px 26px 0px 0px' },
    px: { xs: 1, sm: 1.5 },
    pt: { xs: 2, sm: 3 },
    boxShadow: '-5px 4px 59.8px rgba(24, 84, 153, 0.3)',
  },
  imageStyle: {
    width: '100%',
    mx: 'auto',
    maxWidth: '1082px',
    height: 'auto',
    display: 'block',
  },
};

export {
  COUNTRY_HERO_STYLE,
  LETS_WORK_TOGETHER_STYLE,
  COMPARISON_TABLE_STYLE,
  SALARY_DATA_TABLE_STYLE,
  RIGHT_CHOICE_FOR_EMPLOYERS_STYLE,
  OUT_SOURCING_SERVICES_STYLE,
  COMPANIES_TRUST_STYLE,
  DASHBOARD_HERO_STYLE,
};
