import "./globals.css";
import Loading from "./components/loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Loading>{children}</Loading>
      </body>
    </html>
  );
}
